In [1]:
import numpy as np 

In [2]:
vara = np.arange(15)

In [3]:
vara

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
vara.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
type(vara)

numpy.ndarray

In [8]:
vara.shape

(15,)

In [10]:
vara

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
vara = np.arange(15).reshape(3,5)

In [12]:
vara

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
varb = np.array([6,7,8])

In [15]:
varb.shape

(3,)

In [17]:
varb

array([6, 7, 8])

In [18]:
vara

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
vara.dtype

dtype('int64')

In [20]:
varb = np.array([(1.5, 2, 3), (4,5,6)])

In [21]:
varb.dtype

dtype('float64')

In [22]:
varb

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [23]:
varb.shape

(2, 3)

In [26]:
type(varb[1])

numpy.ndarray

In [33]:
varc = np.array([[1.5, 2], [4,5]], dtype=complex)

In [34]:
varc

array([[1.5+0.j, 2. +0.j],
       [4. +0.j, 5. +0.j]])

In [38]:
vary = np.zeros( (3,4) )

In [39]:
vary

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
varz = np.ones( (2,3) )

In [41]:
varz

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
vara = np.arange(6)

In [45]:
vara

array([0, 1, 2, 3, 4, 5])

In [46]:
print(vara)

[0 1 2 3 4 5]


In [47]:
varb = np.arange(12).reshape(4,3)

In [48]:
print(varb)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [49]:
varb

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
varb = np.arange(12).reshape(4,3)

In [52]:
varc = np.arange(12).reshape(2,3,2)

In [53]:
print(varc)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [54]:
varc = np.arange(24).reshape(2,3,4)

In [55]:
print(varc)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [56]:
varc.reshape(2,3,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [57]:
vard = varc.reshape(2,3,2,2)

In [58]:
vard[1][1][1][1]

19

In [59]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [60]:
#np.set_printoptions(threshold=np.nan)

In [61]:
vara = np.array([20,30,40,50])

In [62]:
varb = np.arange(4)

In [63]:
varb

array([0, 1, 2, 3])

In [64]:
varc = vara-varb 

In [65]:
varc

array([20, 29, 38, 47])

In [66]:
varb**2

array([0, 1, 4, 9])

In [67]:
sum(varb)

6

In [68]:
10 * np.sin(vara)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [70]:
vara

array([20, 30, 40, 50])

In [71]:
vara < 36

array([ True,  True, False, False])